# Generated by Django 4.1.7 on 2023-03-16 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import luch_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Awaiting Email Verification'), (1, 'Awaiting Review'), (2, 'Awaiting Delivery'), (3, 'Delivering'), (4, 'Delivered'), (5, 'Received'), (6, 'Canceled')], default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('started_delivery_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_timestamp', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('^\\d{3,19}$')])),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=22)),
                ('last_name', models.CharField(max_length=22)),
                ('address', models.CharField(max_length=120)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=8)),
                ('price', models.FloatField()),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luch_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luch_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(default=luch_app.models.order_access_key_default_key, max_length=32)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('forcibly_invalid', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
    ]
